<?php
$time_format_options = array("12","24");
$options = array (
	array("name" => "General",
		"type" => "heading"),
	
	array("name" => "Date format",
		"desc" => "Choose date format",
		"id" => PLUGIN_SHORT_NAME."_date_format",
		"std" => "d.m.y",
		"type" => "text"),
	
	array("name" => "Time format",
		"desc" => "Choose whether to display the time in 12 or 24 hour format",
		"id" => PLUGIN_SHORT_NAME."_time_format",
		"std" => "12",
		"type" => "text"),
	
	array("name" => "Default color",
		"desc" => "Choose default event color",
		"id" => PLUGIN_SHORT_NAME."_color",
		"std" => "#fff000",
		"type" => "color"), 
	
	array("name" => "Default hover color",
		"desc" => "Choose default event hover color",
		"id" => PLUGIN_SHORT_NAME."_hover_color",
		"std" => "#000fff",
		"type" => "color")
	
/*
	array("name" => "Username",
		"desc" => "",
		"id" => PLUGIN_SHORT_NAME."_barclays_username",
		"std" => "",
		"type" => "text"), 
	
	array("name" => "Password",
		"desc" => "",
		"id" => PLUGIN_SHORT_NAME."_barclays_password",
		"std" => "",
		"type" => "text"), 
	
	array("name" => "Mode",
		"desc" => "Test = T, Y = Yes (Test), N = No (Test), P = Production",
		"id" => PLUGIN_SHORT_NAME."_barclays_mode",
		"std" => "",
		"type" => "text"), 
	*/
	
	/*
	array(	"name" => "Display setting",
	"type" => "heading"),
	
	array(  "name" => "Custom Logo Image URL",
	"desc" => "Use this if you want to change Logo Image, recommended 237x64 pixel",
	"id" => $shortname."_logo",
	"std" => "",
	"type" => "text"),*/    
	/*array(	"name" => "Slideshow setting",
	"type" => "heading"),         					
	array(	"name" => "Slideshow options",
	"desc" => "Pelase choose your slideshow type as default in the homepage.",
	"id" => $shortname."_opt_slideshow",
	"std" => "3D Slideshow",
	"type" => "select",
	"options" => $slide_options),
	array(	"name" => "Select Category to display in slideshow",
	"desc" => "Please select your category",
	"id" => $shortname."_featured_cat",
	"std" => "",
	"type" => "select",
	"options" => $categories),
	array(	"name" => "Number of post to display in slideshow",
	"desc" => "Select the number of post to display in slideshow.",
	"id" => $shortname."_featured_number",
	"std" => "2",
	"type" => "select",
	"options" => $num_options),
	array(	"name" => "Welcome Message",
	"type" => "heading"),			
	array(	"name" => "Title",
	"desc" => "Welcome Message.",
	"id" => $shortname."_welcome_message",
	"type" => "text"),
	array(	"name" => "Short Description",
	"desc" => "Short Text for Website Description.",
	"id" => $shortname."_site_desc",
	"type" => "textarea"),*/
	
	/*
	array(	"name" => "Menu Options",
	"type" => "heading"),
	array( "name" => "Exclude pages navigation",
	"desc" => "Enter a comma-separated list of the <a href='http://codex.wordpress.org/wp_list_pages#Include_Pages_in_List'>ID's</a> that you'd like to exclude from the top navigation. (e.g. 1,2,3,4)",
	"id" => $shortname."_exclude_pages",
	"std" => "",
	"type" => "text"),   
	array(	"name" => "Page Section",
	"type" => "heading"),    
	array(	"name" => "About page ID",
	"desc" => "Enter the page id from your About page, this will appear in homepage footer.",
	"id" => $shortname."_about_pid",
	"std" => "",
	"type" => "text"), 
	array(	"name" => "News page ID",
	"desc" => "Enter the page id from your Blog page, this is used on the homepage.",
	"id" => $shortname."_news_pid",
	"std" => "",
	"type" => "text"), 
	array(	"name" => "Service parent page ID",
	"desc" => "Enter the parent page id from your Service page, this will retrieve child page from parent Service page.",
	"id" => $shortname."_services_pid",
	"std" => "",
	"type" => "text"),
	array(	"name" => "Category Section",
	"type" => "heading"),
	array(	"name" => "News Category ID",
	"desc" => "Enter the Category ID from your News Category",
	"id" => $shortname."_news_cid",
	"std" => "",
	"type" => "text"),              
	array(	"name" => "Portfolio Category ID",
	"desc" => "Enter the Category ID from your Portfolio Category",
	"id" => $shortname."_portfolio_cid",
	"std" => "",
	"type" => "text"),                                                            
	array(	"name" => "Social Profile Setup",
	"type" => "heading"),
	array(	"name" => "Twitter ID",
	"desc" => "Enter your twitter profile ID here.",
	"id" => $shortname."_twitter_id",
	"std" => "",
	"type" => "text"),
	array(	"name" => "Facebook ID",
	"desc" => "Enter your Facebook profile ID here.",
	"id" => $shortname."_facebook_id",
	"std" => "",
	"type" => "text"),
	array(	"name" => "Linkedin ID",
	"desc" => "Enter your Linkedin profile ID here.",
	"id" => $shortname."_linkedin_id",
	"std" => "",
	"type" => "text"),
	array(	"name" => "Youtube ID",
	"desc" => "Enter your Youtube profile ID here.",
	"id" => $shortname."_youtube_id",
	"std" => "",
	"type" => "text"),
	array(	"name" => "Feedburner ID",
	"desc" => "Enter your Feedburner ID here.",
	"id" => $shortname."_feedburner_id",
	"std" => "",
	"type" => "text"),     
	array(	"name" => "Flickr ID",
	"desc" => "Enter your Flickr ID here. Use <a href=\"http://www.idgettr.com\">IDGettr</a> to find it.",
	"id" => $shortname."_flickr_user",
	"std" => "",
	"type" => "text"),  
	array(	"name"  => "Footer Text",
	"type" => "heading"),
	array(	"name" => "Footer text title",
	"desc" => "Enter the title footer text here.",
	"id" => $shortname."_footer_text_title",
	"std" => "",
	"type" => "text"),            
	array(	"name" => "Footer text ",
	"desc" => "Enter the short footer text here.",
	"id" => $shortname."_footer_text",
	"std" => "",
	"type" => "textarea"),            
	array(	"name" => "Footer Copyright",
	"desc" => "Enter your copyright information here (eg : Copyright 2009, Your company).",
	"id" => $shortname."_footer_copyright",
	"std" => "",
	"type" => "text") */          
);
?>